name: Lint
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Node.Js
      uses: actions/setup-node@v2
      with:
        node-version: '12.x'
    - name: Change current directory to frontend
    - run: cd ./frontend
    - name: Install dependencies
      run: yarn
    - name: Run linter
      run: yarn lint