name: Lint
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Node.Js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: yarn --cwd frontend
    - name: Run linter
      run: yarn --cwd frontend lint